### ISSUE TITLE
FutureWarning in python 3.8

### ISSUE THREAD

**Issue by arogl** [snejus/beets-bandcamp#14]
I get the following error in [_metagurup.py](https://github.com/snejus/beets-bandcamp/blob/master/beetsplug/bandcamp/_metaguru.py#L103)

```
/home/arogl/.local/lib/python3.8/site-packages/beetsplug/bandcamp/_metaguru.py:103: FutureWarning: Possible nested set at position 5
  track["main_title"] = re.sub(r"\s?([[(]|f(ea)?t\.).*", "", track["title"])
```

Found a report and fix. will try a PR

[pycodestyle #735](https://github.com/PyCQA/pycodestyle/pull/735)

**Comment by snejus** [comment]
Fixed through #15
